name: "Build and test .NET SDK"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'

      - name: Build SDK
        run: dotnet build

      - name: Sign assemblies with SNK
        run: |
          snk_path="./key.snk"
          
          # Sign the assemblies with SNK
          find ./src/bin -name '*.dll' -exec sn -R $snk_path {} \;

      - name: Test SDK
        run: dotnet test
